name: BharatCore
version: 1.0
main: com.bharat.bharatcore.BharatCore
api-version: 1.19
author: Bharat
description: Core plugin for Bharat SMP

commands:
  bharat:
    description: Check BharatCore status
    usage: /bharat
